---
- name: Adicionar chave pública ao authorized_keys
  hosts: all
  become: true
  vars_files:
    - ../ansibleProvisioner/vars/vars.yml
    tasks:
      - name: Criar diretório .ssh na VM
        ansible.builtin.file:
          path: /home/vagrant/.ssh
          state: directory
          owner: vagrant
          group: vagrant
          mode: '0700'

    - name: Adicionar chave pública ao authorized_keys
        ansible.builtin.authorized_key:
         user: vagrant
          key: "{{ lookup('file', ssh_public_key_path) }}"
          state: present
          path: /home/vagrant/.ssh/authorized_keys

